
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[menu]
  [[menu.header]]
    name = "About"
    title = "About Blogophonic"
    url = "/about/"
    weight = 1
  [[menu.header]]
    name = "Blog"
    title = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.header]]
    name = "Projects"
    title = "Project Portfolio"
    url = "/project/"
    weight = 3
  [[menu.header]]
    name = "Talks"
    title = "Talks"
    url = "/talk/"
    weight = 4
    
  # Configure footer  
  [[menu.footer]]
    name = "License"
    title = "License"
    url = "/license/"
    weight = 1
  [[menu.footer]]
    name = "Contact"
    title = "Contact form"
    url = "/contact/"
    weight = 2

# see https://gohugo.io/about/hugo-and-gdpr/    
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
